# Generated by Django 5.0.4 on 2026-04-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='link_token',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Токен привязки Telegram'),
        ),
    ]
