# Generated by Django 5.0.4 on 2026-04-12 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('user.register', 'Регистрация'), ('user.login', 'Вход'), ('user.logout', 'Выход'), ('user.ban', 'Блокировка'), ('role.assign', 'Назначение роли'), ('role.revoke', 'Снятие роли'), ('giveaway.create', 'Создание розыгрыша'), ('giveaway.draw', 'Подведение итогов'), ('giveaway.cancel', 'Отмена розыгрыша'), ('punishment.issue', 'Выдача наказания'), ('punishment.revoke', 'Отмена наказания'), ('appeal.resolve', 'Решение апелляции'), ('settings.change', 'Изменение настроек'), ('role.create', 'Создание роли'), ('role.delete', 'Удаление роли')], max_length=50, verbose_name='Действие')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Кто сделал')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_target', to=settings.AUTH_USER_MODEL, verbose_name='Над кем')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('punishment_type', models.CharField(choices=[('warning', 'Предупреждение'), ('mute', 'Мут'), ('ban', 'Бан')], max_length=20, verbose_name='Тип')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('twitch', 'Twitch'), ('all', 'Все платформы'), ('site', 'Сайт')], default='all', max_length=20, verbose_name='Платформа')),
                ('status', models.CharField(choices=[('active', 'Активное'), ('expired', 'Истекло'), ('revoked', 'Отменено')], default='active', max_length=20, verbose_name='Статус')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменено в')),
                ('ai_detected', models.BooleanField(default=False, verbose_name='Обнаружено AI')),
                ('ai_confidence', models.FloatField(blank=True, null=True, verbose_name='Уверенность AI (%)')),
                ('ai_category', models.CharField(blank=True, max_length=50, verbose_name='Категория AI')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_punishments', to=settings.AUTH_USER_MODEL, verbose_name='Выдал')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_punishments', to=settings.AUTH_USER_MODEL, verbose_name='Отменил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punishments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Наказание',
                'verbose_name_plural': 'Наказания',
                'db_table': 'punishments',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('clarify', 'Запрошено уточнение')], default='pending', max_length=20, verbose_name='Статус')),
                ('text', models.TextField(verbose_name='Текст апелляции')),
                ('moderator_response', models.TextField(blank=True, verbose_name='Ответ модератора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Рассмотрена')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appeals', to=settings.AUTH_USER_MODEL, verbose_name='Рассмотрел')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('punishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='moderation.punishment', verbose_name='Наказание')),
            ],
            options={
                'verbose_name': 'Апелляция',
                'verbose_name_plural': 'Апелляции',
                'db_table': 'appeals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('category', models.CharField(choices=[('general', 'Общий вопрос'), ('prize', 'Проблема с призом'), ('punishment', 'Наказание'), ('bug', 'Ошибка на сайте'), ('other', 'Другое')], default='general', max_length=20, verbose_name='Категория')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('in_work', 'В работе'), ('waiting', 'Ожидает ответа'), ('closed', 'Закрыт')], default='open', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыт')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Назначен модератору')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тикет',
                'verbose_name_plural': 'Тикеты',
                'db_table': 'tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('is_staff', models.BooleanField(default=False, verbose_name='От модератора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='moderation.ticket', verbose_name='Тикет')),
            ],
            options={
                'verbose_name': 'Сообщение тикета',
                'verbose_name_plural': 'Сообщения тикетов',
                'db_table': 'ticket_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
