# Generated by Django 5.0.4 on 2026-04-17 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка на клип')),
                ('game', models.CharField(blank=True, default='', max_length=100, verbose_name='Игра')),
                ('preview_url', models.URLField(blank=True, default='', verbose_name='Превью')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='pending', max_length=20, verbose_name='Статус')),
                ('admin_note', models.TextField(blank=True, default='', verbose_name='Заметка администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_clips', to=settings.AUTH_USER_MODEL, verbose_name='Предложил')),
            ],
            options={
                'verbose_name': 'Клип',
                'verbose_name_plural': 'Клипы',
                'db_table': 'clips',
                'ordering': ['-created_at'],
            },
        ),
    ]
