# Generated by Django 5.0.4 on 2026-04-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_new', models.TextField(default='👋 Добро пожаловать! <b>{name}</b>\n\n🎮 <b>VOLTAGE Platform</b> — розыгрыши скинов CS2 и других призов.\n\nВыбери что тебя интересует:', verbose_name='Приветствие (новый пользователь)')),
                ('welcome_back', models.TextField(default='👋 С возвращением! <b>{name}</b>\n\nВыбери раздел:', verbose_name='Приветствие (возвращающийся)')),
                ('giveaway_post_template', models.TextField(default='🎁 <b>РОЗЫГРЫШ: {title}</b>\n\n{description}\n\n👥 Участников: {count}\n⏰ Итоги: {ends_at}\n\n👇 Нажми кнопку чтобы участвовать!', verbose_name='Шаблон поста розыгрыша')),
                ('join_button_text', models.CharField(default='🎯 Участвовать', max_length=50, verbose_name='Текст кнопки участия')),
                ('channel_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID Telegram канала')),
                ('channel_username', models.CharField(blank=True, max_length=100, verbose_name='Username канала (@voltage)')),
                ('chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID чата канала')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки бота',
                'verbose_name_plural': 'Настройки бота',
                'db_table': 'bot_settings',
            },
        ),
    ]
