# Generated by Django 5.0.4 on 2026-04-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Команда')),
                ('response', models.TextField(verbose_name='Ответ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('cooldown', models.PositiveIntegerField(default=5, verbose_name='Кулдаун (сек)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Команда Twitch',
                'verbose_name_plural': 'Команды Twitch',
                'db_table': 'twitch_commands',
                'ordering': ['name'],
            },
        ),
    ]
