# Generated by Django 5.0.4 on 2026-04-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_twitchcommand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_id', models.CharField(max_length=50, unique=True, verbose_name='Twitch ID')),
                ('twitch_login', models.CharField(max_length=50, verbose_name='Twitch логин')),
                ('channel_id', models.CharField(max_length=50, verbose_name='ID канала')),
                ('watch_time_minutes', models.PositiveIntegerField(default=0, verbose_name='Время просмотра (мин)')),
                ('messages_count', models.PositiveIntegerField(default=0, verbose_name='Сообщений')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Последний раз в чате')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='Первый раз в чате')),
            ],
            options={
                'verbose_name': 'Статистика зрителя',
                'verbose_name_plural': 'Статистика зрителей',
                'db_table': 'viewer_stats',
                'unique_together': {('twitch_id', 'channel_id')},
            },
        ),
    ]
