# Generated by Django 5.0.4 on 2026-04-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_viewerstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='schedule',
            field=models.JSONField(blank=True, default=list, verbose_name='Расписание стримов'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='show_giveaways',
            field=models.BooleanField(default=True, verbose_name='Показывать розыгрыши'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='show_moments',
            field=models.BooleanField(default=False, verbose_name='Показывать лучшие моменты'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='show_rules',
            field=models.BooleanField(default=True, verbose_name='Показывать правила'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='show_schedule',
            field=models.BooleanField(default=True, verbose_name='Показывать расписание'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='show_winners',
            field=models.BooleanField(default=True, verbose_name='Показывать победителей'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='streamer_avatar_url',
            field=models.URLField(blank=True, default='', verbose_name='URL аватара'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='streamer_description',
            field=models.TextField(blank=True, default='', verbose_name='Описание стримера'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='streamer_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Имя стримера'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='telegram_url',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ссылка Telegram'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='twitch_url',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ссылка Twitch'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='vk_url',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ссылка VK'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='youtube_url',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ссылка YouTube'),
        ),
    ]
