# Generated by Django 5.0.4 on 2026-04-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_botsettings_schedule_botsettings_show_giveaways_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='streamer_avatar_file',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Файл аватара'),
        ),
    ]
