# Generated by Django 5.0.4 on 2026-04-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_botsettings_streamer_avatar_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='streamer_avatar_position',
            field=models.CharField(blank=True, default='center center', max_length=20, verbose_name='Фокус аватара'),
        ),
    ]
