# Generated by Django 5.0.4 on 2026-04-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_botsettings_streamer_avatar_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='streamer_features',
            field=models.JSONField(blank=True, default=list, verbose_name='Фичи на странице входа'),
        ),
    ]
