# Generated by Django 5.0.4 on 2026-04-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_botsettings_streamer_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='rules_appeals_text',
            field=models.TextField(blank=True, default='Если вы считаете, что наказание было выдано по ошибке, вы можете подать запрос на пересмотр дела. Модераторы рассмотрят вашу заявку в течение 48 часов.', verbose_name='Текст апелляций'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='rules_chat',
            field=models.JSONField(blank=True, default=list, verbose_name='Правила чата'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='rules_giveaway',
            field=models.JSONField(blank=True, default=list, verbose_name='Правила розыгрышей'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='rules_punishments',
            field=models.JSONField(blank=True, default=list, verbose_name='Система наказаний'),
        ),
    ]
