# Generated by Django 5.0.4 on 2026-04-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0008_botsettings_rules_appeals_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='show_schedule_page',
            field=models.BooleanField(default=True, verbose_name='Показывать страницу расписания'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='show_status_page',
            field=models.BooleanField(default=True, verbose_name='Показывать страницу статуса'),
        ),
    ]
