# Generated by Django 5.0.4 on 2026-04-12 00:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Giveaway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название приза')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('prize_type', models.CharField(choices=[('skin', 'Скин CS2'), ('other', 'Другое')], default='skin', max_length=20, verbose_name='Тип приза')),
                ('skin_name', models.CharField(blank=True, max_length=200, verbose_name='Название скина')),
                ('skin_max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Макс. цена скина (руб)')),
                ('skin_image_url', models.URLField(blank=True, verbose_name='Фото скина')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('twitch', 'Twitch'), ('both', 'Оба')], default='telegram', max_length=20, verbose_name='Платформа')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активный'), ('drawing', 'Подведение итогов'), ('finished', 'Завершён'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('require_telegram', models.BooleanField(default=True, verbose_name='Кнопка участвовать в TG')),
                ('require_twitch_stream', models.BooleanField(default=False, verbose_name='Быть на стриме Twitch')),
                ('twitch_keyword', models.CharField(blank=True, max_length=50, verbose_name='Ключевое слово в Twitch чат')),
                ('auto_check_twitch', models.BooleanField(default=True, verbose_name='Автопроверка активности Twitch')),
                ('winner_response_timeout', models.PositiveIntegerField(default=60, verbose_name='Время на ответ победителя (сек)')),
                ('telegram_post_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID поста в Telegram')),
                ('telegram_post_text', models.TextField(blank=True, verbose_name='Текст поста')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('draw_manually', models.BooleanField(default=False, verbose_name='Подвести итоги вручную')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_giveaways', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Розыгрыш',
                'verbose_name_plural': 'Розыгрыши',
                'db_table': 'giveaways',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('responded', 'Ответил'), ('confirmed', 'Подтверждён'), ('rejected', 'Не прошёл проверку'), ('rerolled', 'Перевыбор')], default='pending', max_length=20, verbose_name='Статус')),
                ('twitch_username_provided', models.CharField(blank=True, max_length=50, verbose_name='Twitch ник от победителя')),
                ('twitch_verified', models.BooleanField(null=True, verbose_name='Проверен на Twitch')),
                ('reroll_count', models.PositiveIntegerField(default=0, verbose_name='Количество перевыборов')),
                ('reroll_reason', models.CharField(blank=True, max_length=200, verbose_name='Причина перевыбора')),
                ('drawn_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('giveaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='giveaways.giveaway', verbose_name='Розыгрыш')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to=settings.AUTH_USER_MODEL, verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Победитель',
                'verbose_name_plural': 'Победители',
                'db_table': 'giveaway_winners',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('telegram', 'Telegram кнопка'), ('twitch', 'Twitch keyword'), ('manual', 'Вручную')], default='telegram', max_length=20, verbose_name='Источник')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('giveaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='giveaways.giveaway', verbose_name='Розыгрыш')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'db_table': 'giveaway_participants',
                'unique_together': {('giveaway', 'user')},
            },
        ),
    ]
