# Generated by Django 5.0.4 on 2026-04-12 00:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('giveaways', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('processing', 'Обрабатывается'), ('sent', 'Отправлен'), ('delivered', 'Получен'), ('failed', 'Ошибка доставки'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус')),
                ('delivery_method', models.CharField(choices=[('lisskins', 'LisSkins API'), ('inventory', 'Из инвентаря бота'), ('manual', 'Вручную')], default='lisskins', max_length=20, verbose_name='Метод доставки')),
                ('steam_trade_url', models.URLField(blank=True, verbose_name='Steam Trade URL')),
                ('lisskins_order_id', models.CharField(blank=True, max_length=100, verbose_name='ID заказа LisSkins')),
                ('trade_offer_id', models.CharField(blank=True, max_length=100, verbose_name='ID трейд оффера Steam')),
                ('error_message', models.TextField(blank=True, verbose_name='Текст ошибки')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Попыток отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('winner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prize', to='giveaways.winner', verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Приз',
                'verbose_name_plural': 'Призы',
                'db_table': 'prizes',
                'ordering': ['-created_at'],
            },
        ),
    ]
